# Gopkg.toml example

[[constraint]]
  name = "github.com/Jeffail/benthos"
  version = "1.16.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.10.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.3.0"
